namespace DalTest;
using DalApi;
using DO;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using System.Security.Cryptography;
using System.Data;

static public class Initialization
{
    private static IDal? s_dal;
    //private static IAssignment? s_dalAssignment; // stage 1
    //private static ICall? s_dalCall; // stage 1
    //private static IVolunteer? s_dalVolunteer; // stage 1
    //private static IConfig? s_dalConfig; // stage 1

    private static readonly Random s_rand = new();

    //Be aware that the dummy data has been generated by AI !!!
    static string[] s_names = new string[] {
    "John Smith", "Jane Doe", "Michael Johnson", "Emily Davis", "David Brown",
    "Sarah Wilson", "James Jones", "Jessica Garcia", "Robert Miller", "Mary Martinez",
    "William Anderson", "Linda Taylor", "Richard Thomas", "Barbara Hernandez", "Joseph Moore",
    "Susan Martin", "Charles Jackson", "Margaret Thompson", "Christopher White", "Patricia Harris",
    "Daniel Lewis", "Jennifer Clark", "Matthew Robinson", "Elizabeth Walker", "Anthony Hall",
    "Karen Allen", "Mark Young", "Nancy King", "Paul Wright", "Betty Scott",
    "Steven Green", "Sandra Adams", "Andrew Baker", "Ashley Gonzalez", "Joshua Nelson",
    "Kimberly Carter", "Kevin Mitchell", "Donna Perez", "Brian Roberts", "Carol Turner",
    "Edward Phillips", "Michelle Campbell", "Ronald Parker", "Amanda Evans", "Timothy Edwards",
    "Melissa Collins", "Jason Stewart", "Deborah Sanchez", "Jeffrey Morris", "Stephanie Rogers",
    "Ryan Reed", "Rebecca Cook", "Jacob Morgan", "Laura Bell", "Gary Murphy",
    "Sharon Bailey", "Nicholas Rivera", "Cynthia Cooper", "Eric Richardson", "Kathleen Cox",
    "Stephen Howard", "Amy Ward", "Jonathan Torres", "Angela Peterson", "Larry Gray",
    "Helen Ramirez", "Scott James", "Anna Watson", "Frank Brooks", "Ruth Kelly",
    "Justin Sanders", "Brenda Price", "Brandon Bennett", "Pamela Wood", "Samuel Barnes",
    "Nicole Ross", "Gregory Henderson", "Katherine Coleman", "Benjamin Jenkins", "Christine Perry",
    "Patrick Powell", "Samantha Long", "Raymond Patterson", "Janet Hughes", "Jack Flores",
    "Maria Washington", "Dennis Butler", "Heather Simmons", "Jerry Foster", "Diane Gonzales",
    "Tyler Bryant", "Rachel Alexander", "Aaron Russell", "Catherine Griffin", "Henry Diaz",
    "Julie Hayes", "Adam Myers", "Victoria Ford", "Nathan Hamilton", "Megan Graham"
};
    static string[] s_emails = new string[] {
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com",
    "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com", "meirandesti770@gmail.com"

};
    static string[] s_addresses = new string[] {
        "1 Rothschild Blvd, Tel Aviv",
        "2 Herzl St, Tel Aviv",
        "3 Dizengoff St, Tel Aviv",
        "4 Ibn Gabirol St, Tel Aviv",
        "5 Allenby St, Tel Aviv",
        "6 King George St, Tel Aviv",
        "7 Ben Yehuda St, Tel Aviv",
        "8 Jabotinsky St, Tel Aviv",
        "9 Arlozorov St, Tel Aviv",
        "10 Bograshov St, Tel Aviv",
        "11 Frishman St, Tel Aviv",
        "12 Gordon St, Tel Aviv",
        "13 Hayarkon St, Tel Aviv",
        "14 Basel St, Tel Aviv",
        "15 Yehuda Halevi St, Tel Aviv",
        "16 Nahalat Binyamin St, Tel Aviv",
        "17 Lilienblum St, Tel Aviv",
        "18 Montefiore St, Tel Aviv",
        "19 Shabazi St, Tel Aviv",
        "20 Florentin St, Tel Aviv",
        "21 Levinsky St, Tel Aviv",
        "22 Menachem Begin Rd, Tel Aviv",
        "23 Kaplan St, Tel Aviv",
        "24 Hahashmonaim St, Tel Aviv",
        "25 Carlebach St, Tel Aviv",
        "26 Yigal Alon St, Tel Aviv",
        "27 HaMasger St, Tel Aviv",
        "28 Derech Hashalom, Tel Aviv",
        "29 Namir Rd, Tel Aviv",
        "30 Weizmann St, Tel Aviv",
        "31 Shaul Hamelech Blvd, Tel Aviv",
        "32 Yehuda Maccabi St, Tel Aviv",
        "33 Pinkas St, Tel Aviv",
        "34 Nordau Blvd, Tel Aviv",
        "35 Ben Gurion Blvd, Tel Aviv",
        "36 Dizengoff Square, Tel Aviv",
        "37 Rabin Square, Tel Aviv",
        "38 Haneviim St, Jerusalem",
        "39 Jaffa St, Jerusalem",
        "40 King David St, Jerusalem",
        "41 Agron St, Jerusalem",
        "42 Ben Yehuda St, Jerusalem",
        "43 Hillel St, Jerusalem",
        "44 Shlomzion Hamalka St, Jerusalem",
        "45 Keren Hayesod St, Jerusalem",
        "46 Emek Refaim St, Jerusalem",
        "47 Derech Hebron, Jerusalem",
        "48 Derech Beit Lehem, Jerusalem",
        "49 HaPalmach St, Jerusalem",
        "50 Gaza St, Jerusalem",
        "51 HaNasi St, Jerusalem",
        "52 HaRav Kook St, Jerusalem",
        "53 HaNeviim St, Jerusalem",
        "54 HaTzvi St, Jerusalem",
        "55 HaRav Herzog St, Jerusalem",
        "56 HaRav Shmuel Baruch St, Jerusalem",
        "57 HaRav Uziel St, Jerusalem",
        "58 HaRav Kook St, Jerusalem"
    };
    static double[] s_longitudes = new[]
    {
        34.768982,
        34.7697593,
        34.7814586,
        34.7820896,
        34.76603619999999,
        34.7718028,
        34.7680766,
        34.8040512,
        34.7726748,
        34.7686239,
        34.7690543,
        34.7696267,
        34.7644323,
        34.7769711,
        34.7694594,
        34.7700182,
        34.7695263,
        34.7709599,
        34.7645904,
        34.7688602,
        34.769547,
        34.829074,
        34.7867818,
        34.7755696,
        34.7829257,
        34.7918923,
        34.7856299,
        34.80091110000001,
        34.7940383,
        34.789916,
        34.7891321,
        34.7897246,
        34.7878395,
        34.7764528,
        34.7733411,
        34.777208,
        34.7806198,
        35.2237081,
        35.2199263,
        35.2225549,
        35.2217815,
        35.2144516,
        35.2210645,
        35.2225216,
        35.222138,
        35.2181137,
        35.2256433,
        35.2225398,
        35.2086231,
        35.2123937,
        35.2147285,
        35.2208625,
        35.2183468,
        35.21371,
        35.2049358,
        35.207501,
        35.1862849,
        35.2208625,
    };
    static double[] s_latitudes = new[] {
        32.0631703,
32.0633922,
32.0734225,
32.0717615,
32.0735939,
32.0704183,
32.073845,
32.0826326,
32.0876283,
32.0774401,
32.0800026,
32.0824454,
32.0693901,
32.0900797,
32.0614968,
32.0678115,
32.0621853,
32.0648623,
32.0620528,
32.0561926,
32.0596808,
32.092415,
32.0740448,
32.0713059,
32.0682887,
32.05538,
32.0641254,
32.0702864,
32.081776,
32.0845697,
32.0774985,
32.0937031,
32.0911246,
32.0922064,
32.0848172,
32.0746924,
32.0804846,
31.7840593,
31.7818041,
31.772227,
31.7776993,
31.7809509,
31.7795006,
31.7589424,
31.7720844,
31.7625537,
31.7647235,
31.7613369,
31.7648161,
31.771597,
31.7706183,
31.7836425,
31.7842721,
31.768319,
31.76713269999999,
31.786309,
31.7682148,
31.7836425,
    };
    static List<int> local_ids = new List<int>{
214736688, 944163344, 790288914, 860684307, 491841060,
271797797, 224678953, 876357682, 580422707, 736016437,
015710262, 294855739, 927177279, 840073795, 911761997,
118710888, 990811754, 075926642, 333341816, 855673984,
413444225, 360970891, 215679150, 759492275, 186128062,
809069248, 501516488, 582273744, 049649882, 171489503,
193270501, 198615270, 186333423, 967340787, 885527796,
601071350, 151475969, 979327756, 250928918, 461081366,
649428760, 810525477, 055389993, 628431660, 870258480,
764220208, 302384953, 260045125, 800511305, 943180109,
968639823, 059680090, 760189787, 650388325, 958198632,
360225643, 343223152, 056988017, 635802994, 735323511,
557495165, 332568963, 411161987, 494704521, 120118161,
484477351, 951549864, 074755497, 396699563, 945629103,
642446769, 590795191, 145500088, 682482104, 400611257,
199089079, 848194494, 260202437, 222769093, 485817803,
345474001, 768008658, 337571798, 972331482, 534362595,
526282728, 353412075, 878776301, 260592621, 821537263,
937634798, 000832501, 942607862, 481880573, 383577087
};
    static string[] s_phoneNumbers = new string[] {
    "0501234567", "0502345678", "0503456789", "0504567890", "0505678901",
    "0506789012", "0507890123", "0508901234", "0509012345", "0500123456",
    "0521234567", "0522345678", "0523456789", "0524567890", "0525678901",
    "0526789012", "0527890123", "0528901234", "0529012345", "0520123456",
    "0531234567", "0532345678", "0533456789", "0534567890", "0535678901",
    "0536789012", "0537890123", "0538901234", "0539012345", "0530123456",
    "0541234567", "0542345678", "0543456789", "0544567890", "0545678901",
    "0546789012", "0547890123", "0548901234", "0549012345", "0540123456",
    "0551234567", "0552345678", "0553456789", "0554567890", "0555678901",
    "0556789012", "0557890123", "0558901234", "0559012345", "0550123456",
    "0561234567", "0562345678", "0563456789", "0564567890", "0565678901",
    "0566789012", "0567890123", "0568901234", "0569012345", "0560123456",
    "0571234567", "0572345678", "0573456789", "0574567890", "0575678901",
    "0576789012", "0577890123", "0578901234", "0579012345", "0570123456",
    "0581234567", "0582345678", "0583456789", "0584567890", "0585678901",
    "0586789012", "0587890123", "0588901234", "0589012345", "0580123456",
    "0591234567", "0592345678", "0593456789", "0594567890", "0595678901",
    "0596789012", "0597890123", "0598901234", "0599012345", "0590123456",
    "0501111111", "0502222222", "0503333333", "0504444444", "0505555555",
    "0506666666", "0507777777", "0508888888", "0509999999", "0500000000"
};
    static string[] s_passwords = new string[] {
    "PA1212!a", "Qwerty!234", "A1b2C3d4E5", "Zxcvbnm!23", "Passw0rd!@#",
    "SecureP@ss1", "MyP@ssw0rd2", "Admin!23456", "UserP@ss789", "Login!@#123",
    "P@ssword!23", "Qwerty!@#45", "A1b2C3!@#4", "Zxcvbn!@#56", "Pass!@#7890",
    "Secure!@#123", "MyP@ss!@#45", "Admin!@#678", "User!@#9012", "Login!@#345",
    "P@ssw0rd!@#", "Qwerty!@#67", "A1b2C3!@#8", "Zxcvbn!@#90", "Pass!@#1234",
    "Secure!@#567", "MyP@ss!@#89", "Admin!@#012", "User!@#3456", "Login!@#789",
    "P@ssw0rd!@#1", "Qwerty!@#23", "A1b2C3!@#4", "Zxcvbn!@#56", "Pass!@#7890",
    "Secure!@#123", "MyP@ss!@#45", "Admin!@#678", "User!@#9012", "Login!@#345",
    "P@ssw0rd!@#2", "Qwerty!@#34", "A1b2C3!@#5", "Zxcvbn!@#67", "Pass!@#8901",
    "Secure!@#234", "MyP@ss!@#56", "Admin!@#789", "User!@#0123", "Login!@#456",
    "P@ssw0rd!@#3", "Qwerty!@#45", "A1b2C3!@#6", "Zxcvbn!@#78", "Pass!@#9012",
    "Secure!@#345", "MyP@ss!@#67", "Admin!@#890", "User!@#1234", "Login!@#567",
    "P@ssw0rd!@#4", "Qwerty!@#56", "A1b2C3!@#7", "Zxcvbn!@#89", "Pass!@#0123",
    "Secure!@#456", "MyP@ss!@#78", "Admin!@#901", "User!@#2345", "Login!@#678",
    "P@ssw0rd!@#5", "Qwerty!@#67", "A1b2C3!@#8", "Zxcvbn!@#90", "Pass!@#1234",
    "Secure!@#567", "MyP@ss!@#89", "Admin!@#012", "User!@#3456", "Login!@#789",
    "P@ssw0rd!@#6", "Qwerty!@#78", "A1b2C3!@#9", "Zxcvbn!@#01", "Pass!@#2345",
    "Secure!@#678", "MyP@ss!@#90", "Admin!@#123", "User!@#4567", "Login!@#890"
};
    static string[] s_descriptions = new string[] {
        "Request for food delivery",
        "Inquiry about volunteering opportunities",
        "Donation of food items",
        "Request for emergency food assistance",
        "Follow-up on previous food request",
        "Information about food distribution schedule",
        "Request for special dietary needs",
        "Report of missing food delivery",
        "Request for additional food supplies",
        "Feedback on food quality and service",
    };

    //The calls:
    //0-19 : No assignment
    //20-29: Expired
    //30-99: Regular

    //The Volunteers:
    //0-19 : No calls been taken
    //20-29: Took 2 Calls
    //30-69: Took 5 Calls
    //70-99: Took 7 Calls

    //Order of initialization: Volunteers >> Calls >> Assignments

    /// <summary>
    /// Creates Assignment's instances for the db
    /// </summary>
    /// <exception cref="Exception">Throws an exception if the calls database hasn't been generated</exception>
    private static void createAssignments()
    {
        //Gets dbs
        List<Call> listOfCalls = s_dal?.Call?.ReadAll().ToList()
             ?? throw new DalUnGeneratedDependedList("List of Calls hasn't been generated yet");
        List<Volunteer> listOfVolunteers = s_dal?.Volunteer?.ReadAll().ToList()
            ?? throw new DalUnGeneratedDependedList("List of Volunteers hasn't been generated yet");

        Volunteer currentVolunteer;
        Call currentCall;
        int iterations = listOfCalls.Count() > listOfVolunteers.Count()
            ? listOfVolunteers.Count()
            : listOfCalls.Count();

        //For each volunteer we would assign couple of calls to him
        for (int i = 20; i < iterations; i++)
        {
            Console.WriteLine($"Assignment Number {i - 20 + 1} has been created!");
            currentVolunteer = listOfVolunteers[i];
            currentCall = listOfCalls[i];
            if (currentVolunteer.Id == -1 || i == 99)
                Console.WriteLine("");
            //Calculates the delta time between the opening and closing time of the call    
            TimeSpan delta = (currentCall.DeadLine != null)
            ? (TimeSpan)(currentCall.DeadLine - currentCall.OpeningTime)
            : s_dal!.Config!.Clock.AddDays(31) - currentCall.OpeningTime;

            //Sets the start and end date based on the delta time that has been calculated   
            DateTime start = currentCall.OpeningTime.AddDays(s_rand.Next(0, delta.Days));

            //Calculates the delta time between the selected start time and the closing time of the call
            delta = (currentCall.DeadLine != null)
                ? (TimeSpan)(currentCall.DeadLine - start)
                : s_dal!.Config!.Clock.AddDays(31) - start;

            DateTime end = start.AddDays(s_rand.Next(0, delta.Days));

            //Creates the assignment object - the id is generated in the CRUD's create method so there is no need to provide one here 
            Assignment newAssignment = new()
            {
                CallId = currentCall.Id,
                VolunteerId = currentVolunteer.Id,
                TimeOfStarting = start,
                TimeOfEnding = end,
                TypeOfEnding =
                (end > currentCall.DeadLine)
                ? TypeOfEnding.CancellationExpired
                : (i < 15) ? TypeOfEnding.SelfCanceled
                : (i < 30) ? TypeOfEnding.AdminCanceled
                : TypeOfEnding.Treated
            };
            try
            {
                s_dal?.Assignment?.Create(newAssignment);
            }
            catch (Exception error)
            {
                Console.WriteLine(error.Message);
            }
        }
    }
    /// <summary>
    /// Creates new dummy Call instances for the database
    /// </summary>
    private static void createCalls()
    {
        for (int i = 0; i < 100; i++)
        {
            Console.WriteLine($"Call Number {i + 1} has been created!");
            DateTime start = s_dal!.Config!.Clock.AddDays(s_rand.Next(-31, -5));
            int deltaDays = (s_dal.Config!.Clock - start).Days;
            int position = s_rand.Next(0, s_addresses.Length - 1);
            DateTime end = (i < 30 && i >= 20)
                ? start.AddDays(s_rand.Next(1, deltaDays)) // Expired
                : start.AddDays(s_rand.Next(deltaDays, 31)); // Still open

            //New call instance
            Call newCall = new Call
            {
                Id = -1, //A dummy id, it would be replaced with a proper id in the CRUD method
                Type = (DO.CallType)(s_rand.Next(0, 10)),
                FullAddressCall = s_addresses[position],
                Latitude = s_latitudes[position],
                Longitude = s_longitudes[position],
                OpeningTime = start,
                Description = s_descriptions[i % 10],
                DeadLine = end
            };
            try
            {
                s_dal?.Call?.Create(newCall);
            }
            catch (Exception error)
            {
                Console.WriteLine(error.Message);
            }
        }
    }

    /// <summary>
    /// This method accepts a string value and converts it into a hashed value using SHA256 algorithm
    /// </summary>
    /// <param name="originalPassword">The password before hashing</param>
    /// <returns>The password after hashing</returns>
    internal static string GetSHA256HashedPasswordDal(string originalPassword)
    {
        using (SHA256 sha256Hash = SHA256.Create())
        {
            //Converts the chars into bytes and hashes them
            byte[] bytes = sha256Hash.ComputeHash(Encoding.UTF8.GetBytes(originalPassword));

            //Converts back the hashed bytes into a hex value 
            StringBuilder builder = new StringBuilder();
            string hashedPassword = "";
            bytes.ToList().ForEach((byte val) => hashedPassword += val.ToString("x2"));
            return hashedPassword;
        }
    }

    /// <summary>
    /// Creates new dummy Volunteer instances for the database
    /// </summary>
    private static void createVolunteers()
    {

        for (int i = 0; i < 95; i++)
        {
            Console.WriteLine($"Volunteer Number {i + 1} has been created!");
            Volunteer newVolunteer = new Volunteer
            {
                Id = local_ids[i],
                Role = (i == 0) ? UserRole.Admin : UserRole.Volunteer,
                FullName = s_names[i],
                PhoneNumber = s_phoneNumbers[i],
                Email = s_emails[i],
                MaxDistanceToCall = s_rand.Next(1, 30),
                RangeType = TypeOfRange.AirDistance,
                IsActive = (i == 76 || i == 74 || i == 75) ? false : true,
                Password = GetSHA256HashedPasswordDal(s_passwords[i % (s_passwords.Length - 1)]),
                FullCurrentAddress = s_addresses[i % (s_addresses.Length - 1)],
                Latitude = s_latitudes[i % (s_latitudes.Length - 1)],
                Longitude = s_longitudes[i % (s_longitudes.Length - 1)]
            };
            try
            {
                s_dal?.Volunteer?.Create(newVolunteer);
            }
            catch (Exception error)
            {
                Console.WriteLine(error.Message);
            }
        }

    }

    /// <summary>
    /// This method initializes the local database with dummy data using the provided interfaces
    /// </summary>
    /// <param name="dalAssignment">The assignments implementation interfaces</param>
    /// <param name="dalCall"></param>
    /// <param name="dalVolunteer"></param>
    /// <param name="dalConfig"></param>
    /// <exception cref="NullReferenceException"></exception>
    //public static void Do(IDal dal) // stage 2
    public static void Do() // stage 4
    {
        //s_dal = dal ?? throw new NullReferenceException("DAL object can not be null!"); // stage 2
        s_dal = DalApi.Factory.Get; // stage 4

        //Assignment of the interfaces
        //s_dalAssignment = dalAssignment ?? throw new NullReferenceException("DAL object can not be null!"); // Stage 1
        //s_dalCall = dalCall ?? throw new NullReferenceException("DAL object can not be null!"); // Stage 1
        //s_dalVolunteer = dalVolunteer ?? throw new NullReferenceException("DAL object can not be null!"); // Stage 1
        //s_dalConfig = dalConfig ?? throw new NullReferenceException("DAL object can not be null!"); // Stage 1

        //Resetting the system
        Console.WriteLine("Reset Configuration values and List values...");
        //s_dalConfig.Reset(); // Stage 1
        //s_dalAssignment.DeleteAll(); // Stage 1
        //s_dalCall.DeleteAll(); // Stage 1
        //s_dalVolunteer.DeleteAll(); // Stage 1
        s_dal.ResetDB();
        Console.WriteLine("Initializing Db list ...");
        try
        {
            //Initialization the db
            createVolunteers();
            createCalls();
            createAssignments();
        }
        catch (DalUnGeneratedDependedList error)
        {
            Console.WriteLine(error.Message);
        }
    }

}